<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    public function run()
    {
        $permissions = [
            [
                'id'    => 1,
                'title' => 'user_access',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 2,
                'title' => 'user_create',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 3,
                'title' => 'user_edit',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 4,
                'title' => 'user_show',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 5,
                'title' => 'user_delete',
                'created_by'=> 3,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 6,
                'title' => 'permission_access',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 7,
                'title' => 'permission_create',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 8,
                'title' => 'permission_edit',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 9,
                'title' => 'permission_view',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 10,
                'title' => 'permission_delete',
                'created_by'=> 3,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 11,
                'title' => 'role_access',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 12,
                'title' => 'role_create',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 13,
                'title' => 'role_edit',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 14,
                'title' => 'role_view',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 15,
                'title' => 'role_delete',
                'created_by'=> 3,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 16,
                'title' => 'permission_role_access',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 17,
                'title' => 'permission_role_create',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 18,
                'title' => 'permission_role_edit',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 19,
                'title' => 'permission_role_view',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 20,
                'title' => 'permission_role_delete',
                'created_by'=> 3,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 21,
                'title' => 'team_access',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 22,
                'title' => 'team_create',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 23,
                'title' => 'team_edit',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 24,
                'title' => 'team_view',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 25,
                'title' => 'team_delete',
                'created_by'=> 3,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 26,
                'title' => 'team_user_role_access',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,

            ],
            [
                'id'    => 27,
                'title' => 'team_user_role_create',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 28,
                'title' => 'team_user_role_edit',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 29,
                'title' => 'team_user_role_view',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 30,
                'title' => 'team_user_role_delete',
                'created_by'=> 3,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 31,
                'title' => 'task_access',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 32,
                'title' => 'task_create',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 33,
                'title' => 'task_edit',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 34,
                'title' => 'task_view',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 35,
                'title' => 'task_delete',
                'created_by'=> 3,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 36,
                'title' => 'document_access',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 37,
                'title' => 'document_create',
                'created_by'=> 1,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 38,
                'title' => 'document_edit',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 39,
                'title' => 'document_view',
                'created_by'=> 2,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
            [
                'id'    => 40,
                'title' => 'document_delete',
                'created_by'=> 3,
                'updated_by'=>1,
                'deleted_by'=> 1,
            ],
        ];

        Permission::insert($permissions);
    }
}
