<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        $users = [
            [
                'id'                => 1,
                'name'              => 'Application Admin',
                'email'             => 'applicationadmin@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 999999999,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                   
            ],

            [
                'id'                => 2,
                'name'              => 'Application Support',
                'email'             => 'applicationsupport@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 999999999,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            
            ],

            [
                'id'                => 3,
                'name'              => 'Client Admin1',
                'email'             => 'cadmin1@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 1,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],

            [
                'id'                => 4,
                'name'              => 'Client Admin2',
                'email'             => 'cadmin2@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 2,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],

            [
                'id'                => 5,
                'name'              => 'Client Admin3',
                'email'             => 'cadmin3@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 3,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],
            [
                'id'                => 6,
                'name'              => 'Client User1',
                'email'             => 'cuser1@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   =>1,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],
            [
                'id'                => 7,
                'name'              => 'Client User2',
                'email'             => 'cuser2@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 1,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],
            [
                'id'                => 8,
                'name'              => 'Client User3',
                'email'             => 'cuser3@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 2,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],
            [
                'id'                => 9,
                'name'              => 'Client User4',
                'email'             => 'cuser4@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 2,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            
            ],
            [
                'id'                => 10,
                'name'              => 'Client User5',
                'email'             => 'cuser5@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 3,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],
            [
                'id'                => 11,
                'name'              => 'Client User6',
                'email'             => 'cuser6@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   =>3,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],
            [
                'id'                => 12,
                'name'              => 'Tax-Consultant Admin1',
                'email'             => 'taxadmin1@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 4,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],
            [
                'id'                => 13,
                'name'              => 'Tax-Consultant Admin2',
                'email'             => 'taxadmin2@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 5,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],
            [
                'id'                => 14,
                'name'              => 'Tax-Consultant User1',
                'email'             => 'taxuser1@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 4,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],
            [
                'id'                => 15,
                'name'              => 'Tax-Consultant User2',
                'email'             => 'taxuser2@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 4,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],
            [
                'id'                => 16,
                'name'              => 'Tax-Consultant User3',
                'email'             => 'taxuser3@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 5,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
                
            ],
            [
                'id'                => 17,
                'name'              => 'Tax-Consultant User4',
                'email'             => 'taxuser4@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 5,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            ],
            //-------------------------------------------------------------
            [
                'id'                => 18,
                'name'              => 'Client Viewer 1',
                'email'             => 'clientviewer1@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 1,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            ],
            [
                'id'                => 19,
                'name'              => 'Client Viewer 2',
                'email'             => 'clientviewer2@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 1,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            ],
            [
                'id'                => 20,
                'name'              => 'Client Viewer 3',
                'email'             => 'clientviewer3@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 2,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            ],
            [
                'id'                => 21,
                'name'              => 'Client Viewer 4',
                'email'             => 'clientviewer4@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 2,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            ],
            [
                'id'                => 22,
                'name'              => 'Client Viewer 5',
                'email'             => 'clientviewer5@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 3,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            ],
            [
                'id'                => 23,
                'name'              => 'Client Viewer 6',
                'email'             => 'clientviewer6@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 3,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            ],
            [
                'id'                => 24,
                'name'              => 'Tax-Consultant Viewer 1',
                'email'             => 'taxviewer1@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 4,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            ],
            [
                'id'                => 25,
                'name'              => 'Tax-Consultant Viewer 2',
                'email'             => 'taxviewer2@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 4,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            ],
            [
                'id'                => 26,
                'name'              => 'Tax-Consultant Viewer 3',
                'email'             => 'taxviewer3@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 5,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            ],
            [
                'id'                => 27,
                'name'              => 'Tax-Consultant Viewer 4',
                'email'             => 'taxviewer4@mailtrap.com',
                'email_verified_at' => now(),
                'password'          => bcrypt('123456789'),
                'remember_token'    => null,
                'current_team_id'   => 5,
                'created_by'        => 1,
                'updated_by'        => 1,
                'deleted_by'        => 1,
            ],

        ];

        User::insert($users);
    }
}
